### ISSUE TITLE
Blood Differential Table - labitems codes appear to be wrong

### ISSUE THREAD

**Issue by limyzd** [MIT-LCP/mimic-iv#102]
In mimic-iv/concepts/measurement/blood_differential.sql

The codes given are 
    52056, -- Absolute basophil count
    52060, -- Absolute Eosinophil count
    52061, -- Absolute Monocyte Count
    52062, -- Absolute Neutrophil Count   

Which in d_labitems instead are:
52064	Absolute Basophil Count	Blood	Hematology
52068	Absolute Eosinophil Count	Blood	Hematology
52069	Absolute Monocyte Count	Blood	Hematology
52070	Absolute Neutrophil Count	Blood	Hematology

Should this be amended?

**Comment by alistairewj** [comment]
Yes I think so - it looks like the `itemid` are different still:

```sql
select * from mimic_hosp.d_labitems where lower(label) like '%absolute%count%' order by label
```


Row | itemid | label | fluid | category | loinc_code |  
-- | -- | -- | -- | -- | -- | --
1 | 52069 | Absolute Basophil Count | Blood | Hematology | 704-7 |  
2 | 52070 | Absolute CD19 Count | Blood | Hematology | null |  
3 | 52071 | Absolute CD20 Count | Blood | Hematology | null |  
4 | 51130 | Absolute CD3 Count | Blood | Hematology | 8124-0 |  
5 | 51131 | Absolute CD4 Count | Blood | Hematology | 8128-1 |  
6 | 52072 | Absolute CD56 Count | Blood | Hematology | null |  
7 | 51132 | Absolute CD8 Count | Blood | Hematology | 8138-0 |  
8 | 52073 | Absolute Eosinophil Count | Blood | Hematology | 711-2 |  
9 | 51536 | Absolute Lymphocyte Count | Blood | Chemistry | null |  
10 | 51133 | Absolute Lymphocyte Count | Blood | Hematology | 731-0 |  
11 | 52769 | Absolute Lymphocyte Count | Blood | Hematology | null |  
12 | 52074 | Absolute Monocyte Count | Blood | Hematology | 742-7 |  
13 | 52075 | Absolute Neutrophil Count | Blood | Hematology | 751-8 |  
14 | 51162 | CD16/56 Absolute Count | Blood | Hematology | null |  
15 | 51166 | CD19 Absolute Count | Blood | Hematology | null |  
16 | 51170 | CD20 Absolute Count | Blood | Hematology | null |  
17 | 51175 | CD3 Absolute Count | Blood | Hematology | null |  
18 | 51186 | CD5 Absolute Count | Blood | Hematology | null |  
19 | 52093 | CD56 Absolute Count | Blood | Hematology | null

... maybe they changed in v1.0? not sure.

**Comment by alistairewj** [comment]
I overhauled the query. I wrote it with an internal version of MIMIC originally which is why the `itemid` were incorrect. I took a look at the `itemid` values along with their unit of measure:

```sql
WITH perc AS
(
    SELECT itemid, valuenum
    , PERCENTILE_CONT(valuenum, 0.01) OVER (PARTITION BY itemid) AS p1
    , PERCENTILE_CONT(valuenum, 0.05) OVER (PARTITION BY itemid) AS p5
    , PERCENTILE_CONT(valuenum, 0.5) OVER (PARTITION BY itemid) AS p50
    , PERCENTILE_CONT(valuenum, 0.95) OVER (PARTITION BY itemid) AS p95
    , PERCENTILE_CONT(valuenum, 0.99) OVER (PARTITION BY itemid) AS p99
    FROM `physionet-data.mimic_hosp.labevents`
    WHERE itemid IN
    (
        51146, -- basophils
        52069, -- Absolute basophil count
        51199, -- Eosinophil Count
        51200, -- Eosinophils
        52073, -- Absolute Eosinophil count
        51244, -- Lymphocytes
        51245, -- Lymphocytes, Percent
        51690, -- Lymphocytes
        51133, -- Absolute Lymphocyte Count
        51536, -- Absolute Lymphocyte Count
        52769, -- Absolute Lymphocyte Count
        51253, -- Monocyte Count
        51254, -- Monocytes
        52074, -- Absolute Monocyte Count
        51537, -- Absolute Neutrophil
        51256, -- Neutrophils
        51697, -- Neutrophils
        52075, -- Absolute Neutrophil Count
        51143, -- Atypical lymphocytes
        51144, -- Bands (%)
        51218, -- Granulocyte Count
        52135, -- Immature granulocytes (%)
        51251, -- Metamyelocytes
        51257, -- Nucleated Red Cells
        52151 -- NRBC
    )
)
, ct AS
(
    SELECT itemid
    , COUNT(*) AS n
    , MIN(valuenum) AS min_val
    , AVG(p1) AS p1
    , AVG(p5) AS p5
    , AVG(p50) AS p50
    , AVG(p95) AS p95
    , AVG(p99) AS p99
    , MAX(valuenum) AS max_val
    FROM perc
    GROUP BY itemid
)
SELECT di.itemid, di.label
, n, min_val
, p1, p5, p50,p95, p99
, max_val
FROM `physionet-data.mimic_hosp.d_labitems` di
INNER JOIN ct
USING (itemid)
ORDER BY itemid;
```

... gives:


Row | itemid | label | n | min_val | p1 | p5 | p50 | p95 | p99 | max_val |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 51133 | Absolute Lymphocyte Count | 517586 | 0.0 | 0.08 | 0.27 | 1.37 | 3.49 | 6.97 | 754.02 |  
2 | 51143 | Atypical Lymphocytes | 223293 | 0.0 | 0.0 | 0.0 | 0.0 | 4.0 | 10.0 | 100.0 |  
3 | 51144 | Bands | 242318 | 0.0 | 0.0 | 0.0 | 0.0 | 10.0 | 21.0 | 100.0 |  
4 | 51146 | Basophils | 1294505 | 0.0 | 0.0 | 0.0 | 0.4 | 1.2 | 2.2 | 63.0 |  
5 | 51199 | Eosinophil Count | 531 | 0.0 | 10.0 | 30.0 | 280.0 | 1663.999999999999 | 4064.7999999999984 | 11520.0 |  
6 | 51200 | Eosinophils | 1294505 | 0.0 | 0.0 | 0.0 | 1.5 | 6.6 | 12.6 | 98.0 |  
7 | 51218 | Granulocyte Count | 99590 | 0.0 | 0.0 | 43.45000000000027 | 2920.0 | 9870.0 | 18440.549999999996 | 239700.0 |  
8 | 51244 | Lymphocytes | 1294510 | 0.0 | 1.8 | 4.5 | 21.6 | 50.5 | 87.0 | 100.0 |  
9 | 51245 | Lymphocytes, Percent | 27148 | 0.0 | 3.850000000000001 | 9.0 | 31.0 | 52.0 | 65.0 | 100.0 |  
10 | 51251 | Metamyelocytes | 225553 | 0.0 | 0.0 | 0.0 | 0.0 | 4.0 | 9.0 | 41.0 |  
11 | 51253 | Monocyte Count | 36 | 0.0 | 10.5 | 52.5 | 310.0 | 700.2499999999998 | 1371.9999999999998 | 1680.0 |  
12 | 51254 | Monocytes | 1294509 | 0.0 | 0.0 | 2.0 | 6.3 | 14.5 | 25.0 | 100.0 |  
13 | 51256 | Neutrophils | 1294510 | 0.0 | 2.0 | 31.6 | 66.9 | 89.2 | 94.2 | 100.0 |  
14 | 51257 | Nucleated Red Cells | 83255 | 0.0 | 0.1 | 0.2 | 1.5 | 23.0 | 107.0 | 4093.0 |  
15 | 51697 | Neutrophils | 88 | 0.3 | 0.386 | 0.53 | 1.2 | 2.7 | 3.869999999999999 | 4.3 |  
16 | 52069 | Absolute Basophil Count | 517586 | 0.0 | 0.0 | 0.0 | 0.03 | 0.09 | 0.19 | 31.9 |  
17 | 52073 | Absolute Eosinophil Count | 517630 | 0.0 | 0.0 | 0.0 | 0.09 | 0.48 | 1.06 | 191.7 |  
18 | 52074 | Absolute Monocyte Count | 517587 | 0.0 | 0.0 | 0.07 | 0.57 | 1.43 | 2.55 | 116.03 |  
19 | 52075 | Absolute Neutrophil Count | 539821 | 0.0 | 0.02 | 0.76 | 4.56 | 14.22 | 24.55 | 880.0 |  
20 | 52135 | Immature Granulocytes | 409799 | 0.0 | 0.1 | 0.2 | 0.4 | 1.5 | 3.0 | 24.9 |  
21 | 52769 | Absolute Lymphocyte Count | 27148 | 0.0 | 200.0 | 494.0 | 1696.0 | 3358.0 | 4816.0 | 214760.0

Based on this query I rewrote the blood_differential query to include both absolute counts and percentages. I've added some missed `itemid` and harmonize the percentages/counts now so the table is more complete. I also added WBC to the table and impute absolute counts if the total WBC is available. I didn't exhaustively cover all cell types (there are some rare/unusual ones like spherocytes), but the major ones are covered. Worth noting that as highlighted in #9 the LOINC codes seem incorrect and aren't properly differentiating the unit of measurement. Let me know if you see anything suspicious!

**Comment by limyzd** [comment]
Hi Alistair,
To my knowledge, the percentage for white blood cell diffential counts has the total white blood cells as the denominator. This is the % reported in most blood count reports and not the percentile.

In general it would be quite unusual for total wbc to be unavailable if the absolute counts are, as most analyzers will give total wbc counts. In theory we should be able to pivot out a row for each specimen that gives the total wbc and the constituent differential. 

I think nucleated rbc and spherocyte should be excluded from this list as they are types of rbc, not wbc.

Thanks very much!

**Comment by alistairewj** [comment]
> Hi Alistair,
> To my knowledge, the percentage for white blood cell diffential counts has the total white blood cells as the denominator. This is the % reported in most blood count reports and not the percentile.
> 
> In general it would be quite unusual for total wbc to be unavailable if the absolute counts are, as most analyzers will give total wbc counts. In theory we should be able to pivot out a row for each specimen that gives the total wbc and the constituent differential.

Agreed! I think I have done this, but some QA is always helpful.

> I think nucleated rbc and spherocyte should be excluded from this list as they are types of rbc, not wbc.

Hm fair point. There could be an *rbc* table with the various measures there beyond just the differential (RBC width, etc).
