### ISSUE TITLE
Some questions on sepsis3

### ISSUE THREAD

**Issue by JHLiu7** [MIT-LCP/mimic-iv#112]
Regarding sepsis onset based on sepsis-3 criteria, would using `sofa_time` in the derived `sepsis3` to determine the onset be the recommended choice? Or should I also consider `suspected_infection_time` and use whichever is the latest?

In addition, I noticed there are 12,529 rows in the `sepsis3` table, accounting for 16.3% of the total icu stays (76,540). (It becomes 18.1% if divided by hospital admission count, 69,211). That seems to be a bit different from the number in mimic-iii based on the sepsis3-mimic [repo](https://github.com/alistairewj/sepsis3-mimic) (Great work, by the way! Learned a lot from it), where I believe 5784 cases were identified from 23,620 metavision stays (24.5%). I wonder if that difference is normal.

Finally, I'm also interested to obtain the onset information on mimic-iii (as I'd like to work with clinical notes). Do you recommend adapting the code here to do that? Or are there any other suggestions? Thanks a lot!

**Comment by alistairewj** [comment]
> Regarding sepsis onset based on sepsis-3 criteria, would using `sofa_time` in the derived `sepsis3` to determine the onset be the recommended choice? Or should I also consider `suspected_infection_time` and use whichever is the latest?

There's no great onset time to be honest because the information needed for suspicion of infection can occur before/after the organ failure documentation (`sofa_time`). With that said I would argue that `sofa_time` is the best time for the onset since it's based on the physiology, and hopefully in the future there will be a better definition of suspicion of infection.

> In addition, I noticed there are 12,529 rows in the `sepsis3` table, accounting for 16.3% of the total icu stays (76,540). (It becomes 18.1% if divided by hospital admission count, 69,211). That seems to be a bit different from the number in mimic-iii based on the sepsis3-mimic [repo](https://github.com/alistairewj/sepsis3-mimic) (Great work, by the way! Learned a lot from it), where I believe 5784 cases were identified from 23,620 metavision stays (24.5%). I wonder if that difference is normal.

Thanks! Off the top of my head I don't know. Could be any one of:

* more recent data (2012 onward) and we're better at catching sepsis early
* similar to above, they started taking blood cultures much more routinely during 2008 - 2012 and maybe the first few years biased the numerator down
* change in the ICU stay definition resulting in many subsequent ICU stays which boost the denominator (could adjust for this by taking the first ICU stay in the MIMIC-IV %, I believe this is done in the MIMIC-III analysis)

Worth digging in a bit more.

> Finally, I'm also interested to obtain the onset information on mimic-iii (as I'd like to work with clinical notes). Do you recommend adapting the code here to do that? Or are there any other suggestions? Thanks a lot!

Yeah I'd use the code here - the sepsis3-mimic code forces you to adopt our decision to only look at sepsis in the first 24 hours, whereas the code here allows more flexibility.

**Comment by JHLiu7** [comment]
Awesome, thanks! Very detailed explanations
