### ISSUE TITLE
Many admissions do not have dx code

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#27]
Hi, I run the following query to count the number of admissions using icd9/icd10 code but found many admissions without dx code:
```
select p.anchor_year_group,icd_version, count(distinct ad.hadm_id) as ad_count from `physionet-data.mimic_core.admissions`  as ad
left join `physionet-data.mimic_hosp.diagnoses_icd` as dx
on ad.hadm_id = dx.hadm_id
left join `physionet-data.mimic_core.patients` as p
on p.subject_id = ad.subject_id 
group by icd_version, p.anchor_year_group 
order by p.anchor_year_group 
```

Row | anchor_year_group | icd_version | ad_count |  
-- | -- | -- | -- | --
1 | 2008 - 2010 | 10 | 36000 |  
2 | 2008 - 2010 | null | 74496 |_  
3 | 2008 - 2010 | 9 | 120819 |  
4 | 2011 - 2013 | 9 | 96763 |  
5 | 2011 - 2013 | null | 1796 |  
6 | 2011 - 2013 | 10 | 23110 |  
7 | 2014 - 2016 | 10 | 54068 |  
8 | 2014 - 2016 | 9 | 42165 |  
9 | 2014 - 2016 | null | 2150 |  
10 | 2017 - 2019 | 10 | 70152 |  
11 | 2017 - 2019 | null | 3011 |

**Comment by alistairewj** [comment]
Hm, odd. Nothing jumps to mind about why this would happen but I'll look into it.

**Comment by alistairewj** [comment]
This was caused by an internal data issue - we've since fixed the data pull and this is no longer an issue. For full transparency this issue affected the *diagnoses_icd*, *procedures_icd*, *hcpcsevents*, and *drgcodes* tables. https://mimic-iv.mit.edu/docs/overview/changelog/#mimic-iv-v10


Row | anchor_year_group | icd_version | ad_count |  
-- | -- | -- | -- | --
1 | 2008 - 2010 | 9 | 194705 |  
2 | 2008 - 2010 | 10 | 36157 |  
3 | 2008 - 2010 | null | 449 |  
4 | 2011 - 2013 | 9 | 97790 |  
5 | 2011 - 2013 | 10 | 23204 |  
6 | 2011 - 2013 | null | 371 |  
7 | 2014 - 2016 | 9 | 42881 |  
8 | 2014 - 2016 | 10 | 54736 |  
9 | 2014 - 2016 | null | 470 |  
10 | 2017 - 2019 | 10 | 71645 |  
11 | 2017 - 2019 | null | 1340 |  
12 | 2017 - 2019 | 9 | 2 |  

Thanks for the report!
