### ISSUE TITLE
What was the difference bewteen the category 'Labs' of 'd_items' and 'd_labitems'?

### ISSUE THREAD

**Issue by shaou77** [MIT-LCP/mimic-iv#32]
For example, the albumin, in the category 'Labs' of 'd_items', its itemid was 227456,  in 'd_labitems', its itemid were 50862, 51542 and so on.  I can find results by the two types of itemid. I wonder what was the difference between them. Should I take all of them in my query? Thanks.

**Comment by alistairewj** [comment]
The data from `d_labitems` and `labevents` is from the hospital database. This is the recommended table to pull laboratory data from because:

* the local staff are informed the lab database is the "ground truth" - any requested changes should be done to the laboratory data
* it is available outside the ICU, where as `chartevents` is only available in the ICU
* it has a `specimen_id`, allowing linking to labs drawn from the same specimen (more useful for other labs such as blood gases)

**Comment by shaou77** [comment]
Thank you for your answer and your great work!
